version: '3.8'
services:
  # vue:
  #   build: ./vue
  #   container_name: vue-container
  #   ports:
  #     - '3000:8080'
  #   volumes:
  #     - ./:/vue
  #   tty: true
  api:
    build: ./api
    container_name: go-api-container
    ports:
      - '8080:8080'
    volumes:
      - ./api:/go/src/app
    tty: true