package model

type AutoGenerated struct {
	Pet             Pet `json:"pet"`
	DosageSchedules struct {
		Today struct {
			Name string `json:"name"`
			Date string `json:"date"`
		} `json:"today"`
		Next struct {
			Name string `json:"name"`
			Date string `json:"date"`
		} `json:"next"`
	} `json:"dosage_schedule"`
	PhysicalCondition struct {
		Food   int `json:"food"`
		Sweat  int `json:"sweat"`
		Toilet int `json:"toilet"`
	} `json:"physical_condition"`
	Memo      string     `json:"memo"`
	Schedules []Schedule `json:"schedules"`
}
